### PR TITLE
Add Scala 2.13.1 to crossScalaVersions and update the dependencies

### PR DESCRIPTION
**Pull request by azolotko**

### CODE REVIEW

**Comment by azolotko** [comment]
Tests are failing randomly on Travis CI. I couldn't reproduce it locally, will take a look later.

**Comment by felixbr** [comment]
Hey 🙂

I'm interested in using this with 2.13.1, so I looked at the failing runs on Travis and it seems that the `.unsafeRunTimed(10.seconds)` in the tests is a little too short. Locally I could reproduce the same errors by reducing it to `8.seconds`.

Maybe we can just increase the timeout to `15.seconds` and get this up and running?

**Comment by azolotko** [comment]
@felixbr the last attempt was `.unsafeRunTimed(30.seconds)`, but it still fails randomly. I suspect the problem is bigger than just the properly set timeout.

**Comment by felixbr** [comment]
It seems like I fixed the issue over at #8 🎉

Feel free to cherry-pick my commit onto your PR, as you've done the bulk of the work 🙂

**Comment by felixbr** [comment]
I think you shouldn't update sbt in this PR. If you insist to update sbt, I recommend to use 1.3.4 instead of 1.3.5, as the latter has class loading issues.

**Comment by azolotko** [comment]
@felixbr Thanks Felix. I've also figured this out. The hard way :)

**Comment by azolotko** [comment]
@felixbr The TravisCI build is still failing...

**Comment by felixbr** [comment]
Hm strange, my debug PR (#8) worked on the first try 🤔

**Comment by azolotko** [comment]
@felixbr Great. I'll then just close mine and you can remove `[WIP | Travis-Debug]` from yours and let's hope it'll get merged soon.

**Pull request closed without merging**
